#include <openxr/openxr.h>

#define XR_FOREACH(X)\
  X(xrGetInstanceProcAddr)\
  X(xrEnumerateApiLayerProperties)\
  X(xrEnumerateInstanceExtensionProperties)\
  X(xrCreateInstance)\
  X(xrDestroyInstance)\
  X(xrResultToString)\
  X(xrCreateSpatialAnchorFromPerceptionAnchorMSFT)\
  X(xrTryGetPerceptionAnchorFromSpatialAnchorMSFT)\
  X(xrEnumerateColorSpacesFB)\
  X(xrGetInstanceProcAddr)\
  X(xrEnumerateApiLayerProperties)\
  X(xrEnumerateInstanceExtensionProperties)\
  X(xrCreateInstance)\
  X(xrDestroyInstance)\
  X(xrResultToString)\
  X(xrStructureTypeToString)\
  X(xrGetInstanceProperties)\
  X(xrGetSystem)\
  X(xrGetSystemProperties)\
  X(xrCreateSession)\
  X(xrDestroySession)\
  X(xrDestroySpace)\
  X(xrEnumerateSwapchainFormats)\
  X(xrCreateSwapchain)\
  X(xrDestroySwapchain)\
  X(xrEnumerateSwapchainImages)\
  X(xrAcquireSwapchainImage)\
  X(xrWaitSwapchainImage)\
  X(xrReleaseSwapchainImage)\
  X(xrBeginSession)\
  X(xrEndSession)\
  X(xrRequestExitSession)\
  X(xrEnumerateReferenceSpaces)\
  X(xrCreateReferenceSpace)\
  X(xrCreateActionSpace)\
  X(xrLocateSpace)\
  X(xrEnumerateViewConfigurations)\
  X(xrEnumerateEnvironmentBlendModes)\
  X(xrGetViewConfigurationProperties)\
  X(xrEnumerateViewConfigurationViews)\
  X(xrBeginFrame)\
  X(xrLocateViews)\
  X(xrEndFrame)\
  X(xrWaitFrame)\
  X(xrApplyHapticFeedback)\
  X(xrStopHapticFeedback)\
  X(xrPollEvent)\
  X(xrStringToPath)\
  X(xrPathToString)\
  X(xrGetReferenceSpaceBoundsRect)\
  X(xrSetAndroidApplicationThreadKHR)\
  X(xrCreateSwapchainAndroidSurfaceKHR)\
  X(xrGetActionStateBoolean)\
  X(xrGetActionStateFloat)\
  X(xrGetActionStateVector2f)\
  X(xrGetActionStatePose)\
  X(xrCreateActionSet)\
  X(xrDestroyActionSet)\
  X(xrCreateAction)\
  X(xrDestroyAction)\
  X(xrSuggestInteractionProfileBindings)\
  X(xrAttachSessionActionSets)\
  X(xrGetCurrentInteractionProfile)\
  X(xrSyncActions)\
  X(xrEnumerateBoundSourcesForAction)\
  X(xrGetInputSourceLocalizedName)\
  X(xrGetVulkanInstanceExtensionsKHR)\
  X(xrGetVulkanDeviceExtensionsKHR)\
  X(xrGetVulkanGraphicsDeviceKHR)\
  X(xrGetOpenGLGraphicsRequirementsKHR)\
  X(xrGetOpenGLESGraphicsRequirementsKHR)\
  X(xrGetVulkanGraphicsRequirementsKHR)\
  X(xrGetD3D11GraphicsRequirementsKHR)\
  X(xrGetD3D12GraphicsRequirementsKHR)\
  X(xrPerfSettingsSetPerformanceLevelEXT)\
  X(xrThermalGetTemperatureTrendEXT)\
  X(xrSetDebugUtilsObjectNameEXT)\
  X(xrCreateDebugUtilsMessengerEXT)\
  X(xrDestroyDebugUtilsMessengerEXT)\
  X(xrSubmitDebugUtilsMessageEXT)\
  X(xrSessionBeginDebugUtilsLabelRegionEXT)\
  X(xrSessionEndDebugUtilsLabelRegionEXT)\
  X(xrSessionInsertDebugUtilsLabelEXT)\
  X(xrConvertTimeToWin32PerformanceCounterKHR)\
  X(xrConvertWin32PerformanceCounterToTimeKHR)\
  X(xrCreateVulkanInstanceKHR)\
  X(xrCreateVulkanDeviceKHR)\
  X(xrGetVulkanGraphicsDevice2KHR)\
  X(xrConvertTimeToTimespecTimeKHR)\
  X(xrConvertTimespecTimeToTimeKHR)\
  X(xrGetVisibilityMaskKHR)\
  X(xrCreateSpatialAnchorMSFT)\
  X(xrCreateSpatialAnchorSpaceMSFT)\
  X(xrDestroySpatialAnchorMSFT)\
  X(xrSetInputDeviceActiveEXT)\
  X(xrSetInputDeviceStateBoolEXT)\
  X(xrSetInputDeviceStateFloatEXT)\
  X(xrSetInputDeviceStateVector2fEXT)\
  X(xrSetInputDeviceLocationEXT)\
  X(xrInitializeLoaderKHR)\
  X(xrCreateSpatialGraphNodeSpaceMSFT)\
  X(xrCreateHandTrackerEXT)\
  X(xrDestroyHandTrackerEXT)\
  X(xrLocateHandJointsEXT)\
  X(xrCreateHandMeshSpaceMSFT)\
  X(xrUpdateHandMeshMSFT)\
  X(xrGetControllerModelKeyMSFT)\
  X(xrLoadControllerModelMSFT)\
  X(xrGetControllerModelPropertiesMSFT)\
  X(xrGetControllerModelStateMSFT)\
  X(xrEnumerateDisplayRefreshRatesFB)\
  X(xrGetDisplayRefreshRateFB)\
  X(xrRequestDisplayRefreshRateFB)\
  X(xrCreateSpatialAnchorFromPerceptionAnchorMSFT)\
  X(xrTryGetPerceptionAnchorFromSpatialAnchorMSFT)\
  X(xrEnumerateColorSpacesFB)\
  X(xrGetInstanceProcAddr)\
  X(xrEnumerateApiLayerProperties)\
  X(xrEnumerateInstanceExtensionProperties)\
  X(xrCreateInstance)\
  X(xrDestroyInstance)\
  X(xrResultToString)\
  X(xrStructureTypeToString)\
  X(xrGetInstanceProperties)\
  X(xrGetSystem)\
  X(xrGetSystemProperties)\
  X(xrCreateSession)\
  X(xrDestroySession)\
  X(xrDestroySpace)\
  X(xrEnumerateSwapchainFormats)\
  X(xrCreateSwapchain)\
  X(xrDestroySwapchain)\
  X(xrEnumerateSwapchainImages)\
  X(xrAcquireSwapchainImage)\
  X(xrWaitSwapchainImage)\
  X(xrReleaseSwapchainImage)\
  X(xrBeginSession)\
  X(xrEndSession)\
  X(xrRequestExitSession)\
  X(xrEnumerateReferenceSpaces)\
  X(xrCreateReferenceSpace)\
  X(xrCreateActionSpace)\
  X(xrLocateSpace)\
  X(xrEnumerateViewConfigurations)\
  X(xrEnumerateEnvironmentBlendModes)\
  X(xrGetViewConfigurationProperties)\
  X(xrEnumerateViewConfigurationViews)\
  X(xrBeginFrame)\
  X(xrLocateViews)\
  X(xrEndFrame)\
  X(xrWaitFrame)\
  X(xrApplyHapticFeedback)\
  X(xrStopHapticFeedback)\
  X(xrPollEvent)\
  X(xrStringToPath)\
  X(xrPathToString)\
  X(xrGetReferenceSpaceBoundsRect)\
  X(xrSetAndroidApplicationThreadKHR)\
  X(xrCreateSwapchainAndroidSurfaceKHR)\
  X(xrGetActionStateBoolean)\
  X(xrGetActionStateFloat)\
  X(xrGetActionStateVector2f)\
  X(xrGetActionStatePose)\
  X(xrCreateActionSet)\
  X(xrDestroyActionSet)\
  X(xrCreateAction)\
  X(xrDestroyAction)\
  X(xrSuggestInteractionProfileBindings)\
  X(xrAttachSessionActionSets)\
  X(xrGetCurrentInteractionProfile)\
  X(xrSyncActions)\
  X(xrEnumerateBoundSourcesForAction)\
  X(xrGetInputSourceLocalizedName)\
  X(xrGetVulkanInstanceExtensionsKHR)\
  X(xrGetVulkanDeviceExtensionsKHR)\
  X(xrGetVulkanGraphicsDeviceKHR)\
  X(xrGetOpenGLGraphicsRequirementsKHR)\
  X(xrGetOpenGLESGraphicsRequirementsKHR)\
  X(xrGetVulkanGraphicsRequirementsKHR)\
  X(xrGetD3D11GraphicsRequirementsKHR)\
  X(xrGetD3D12GraphicsRequirementsKHR)\
  X(xrPerfSettingsSetPerformanceLevelEXT)\
  X(xrThermalGetTemperatureTrendEXT)\
  X(xrSetDebugUtilsObjectNameEXT)\
  X(xrCreateDebugUtilsMessengerEXT)\
  X(xrDestroyDebugUtilsMessengerEXT)\
  X(xrSubmitDebugUtilsMessageEXT)\
  X(xrSessionBeginDebugUtilsLabelRegionEXT)\
  X(xrSessionEndDebugUtilsLabelRegionEXT)\
  X(xrSessionInsertDebugUtilsLabelEXT)\
  X(xrConvertTimeToWin32PerformanceCounterKHR)\
  X(xrConvertWin32PerformanceCounterToTimeKHR)\
  X(xrCreateVulkanInstanceKHR)\
  X(xrCreateVulkanDeviceKHR)\
  X(xrGetVulkanGraphicsDevice2KHR)\
  X(xrConvertTimeToTimespecTimeKHR)\
  X(xrConvertTimespecTimeToTimeKHR)\
  X(xrGetVisibilityMaskKHR)\
  X(xrCreateSpatialAnchorMSFT)\
  X(xrCreateSpatialAnchorSpaceMSFT)\
  X(xrDestroySpatialAnchorMSFT)\
  X(xrSetInputDeviceActiveEXT)\
  X(xrSetInputDeviceStateBoolEXT)\
  X(xrSetInputDeviceStateFloatEXT)\
  X(xrSetInputDeviceStateVector2fEXT)\
  X(xrSetInputDeviceLocationEXT)\
  X(xrInitializeLoaderKHR)\
  X(xrCreateSpatialGraphNodeSpaceMSFT)\
  X(xrCreateHandTrackerEXT)\
  X(xrDestroyHandTrackerEXT)\
  X(xrLocateHandJointsEXT)\
  X(xrCreateHandMeshSpaceMSFT)\
  X(xrUpdateHandMeshMSFT)\
  X(xrGetControllerModelKeyMSFT)\
  X(xrLoadControllerModelMSFT)\
  X(xrGetControllerModelPropertiesMSFT)\
  X(xrGetControllerModelStateMSFT)\
  X(xrEnumerateDisplayRefreshRatesFB)\
  X(xrGetDisplayRefreshRateFB)\
  X(xrRequestDisplayRefreshRateFB)\
  X(xrCreateSpatialAnchorFromPerceptionAnchorMSFT)\
  X(xrTryGetPerceptionAnchorFromSpatialAnchorMSFT)\
  X(xrEnumerateColorSpacesFB)\
  X(xrSetColorSpaceFB)
